### ISSUE TITLE
How to use it in Angular 14 project?

### ISSUE THREAD

**Issue by andreosky** [iamvanja/poof#1]
I love your idea and I want to integrate it into my PWA. What do I have to do?

**Comment by iamvanja** [comment]
Hi @andreosky ! This project is no longer maintained. 

You can follow example.html to see the dependencies required (modernizer and jquery). Currently poof.js attaches `click touchstart` handlers to entire `document`. In angular you could do something like

`<button (click)='animatePoof()'>Click to poof</button>`
